spring:
  config:
    import: classpath:/application-domain-keyword.yml, classpath:/application-domain-document.yml

logging:
  level:
    root: info
    seolnavy: debug
    org.springframework: info
