app:
  api:
    kakao:
      url: https://dapi.kakao.com
      authorization: KakaoAK
      rest-api-key: reissueCompleted
    naver:
      url: https://openapi.naver.com
      client-id: reissueCompleted
      client-secret: reissueCompleted
